#!/bin/bash
#
# srcleaner	Stone Ridge client cleanup daemon
#
# chkconfig: 2345 98 09
# description: srcleaner is responsible for cleaning up old test runs

### BEGIN INIT INFO
# Provides: srcleaner
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start and stop stoneridge cleaner
# Description: stoneridge cleaner cleans up old test runs
### END INIT INFO

source /etc/default/stoneridge

PID=$SRHOME/srcleaner.pid
LOG=$SRHOME/srcleaner.log

start() {
    python $SRRUN $SRROOT/srcleaner.py --config $CONFFILE --pidfile $PID --log $LOG
}

stop() {
    kill $(cat $PID)
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|force-reload|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|force-reload}"
    exit 2
esac
