#!/bin/bash
#
# srdns	Stone Ridge dns modifier daemon
#
# chkconfig: 2345 98 09
# description: srdns is responsible for modifying dns servers

### BEGIN INIT INFO
# Provides: srdns
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start and stop stoneridge dns modifier daemon
# Description: srdns modifies the dns servers on the machine
### END INIT INFO

source /etc/default/stoneridge

PID=$SRRUNDIR/srdns.pid
LOG=$SRLOGDIR/srdns.log

start() {
    python $SRRUN $SRROOT/srdns.py --config $CONFFILE --pidfile $PID --log $LOG
}

stop() {
    kill $(cat $PID)
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|force-reload|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|force-reload}"
    exit 2
esac
