#!/bin/bash
#
# srinterface	Stone Ridge interface setup
#
# chkconfig: 2345 97 10
# description: srinterface configures the stone ridge network interface

### BEGIN INIT INFO
# Provides: srinterface
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Configure the stone ridge network interface
# Description: Configure the stone ridge network interface
### END INIT INFO

source /etc/default/stoneridge

start() {
    ip addr add $MYIP/12 dev $MYDEV
}

stop() {
    ip addr del $MYIP/12 dev $MYDEV
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|force-reload|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|force-reload}"
    exit 2
esac
