#!/bin/bash
#
# srworker	Stone Ridge worker process
#
# chkconfig: 2345 98 09
# description: srworker is responsible for running tests

### BEGIN INIT INFO
# Provides: srworker
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start and stop stoneridge worker
# Description: stoneridge worker runs tests
### END INIT INFO

source /etc/default/stoneridge

PID=$SRHOME/srworker.pid
LOG=$SRHOME/srworker.log

start() {
    python $SRRUN $SRROOT/srworker.py --config $CONFFILE --pidfile $PID --log $LOG
}

stop() {
    kill $(cat $PID)
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|force-reload|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|force-reload}"
    exit 2
esac
