#!/bin/bash
#
# smaster	Stone Ridge master process
#
# chkconfig: 2345 98 09
# description: smaster is responsible for cloning builds and distributing \
#              tests to the servers for scheduling

### BEGIN INIT INFO
# Provides: smaster
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start and stop stoneridge master
# Description: stoneridge master clones builds and distributes tests
### END INIT INFO

source /etc/default/stoneridge

PID=$SRRUNDIR/srmaster.pid
LOG=$SRLOGDIR/srmaster.log

start() {
    python $SRRUN $SRROOT/srmaster.py --config $CONFFILE --pidfile $PID --log $LOG
}

stop() {
    kill $(cat $PID)
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|force-reload|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|force-reload}"
    exit 2
esac
