#!/bin/bash
#
# srmqproxy	Stone Ridge MQ Proxy setup
#
# chkconfig: 2345 98 09
# description: srmqproxy is part of a hack to make windows work better

### BEGIN INIT INFO
# Provides: srreporter
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start and stop stoneridge mq proxy
# Description: stoneridge mq proxy takes things out of rabbitmq and puts them in our web mq
### END INIT INFO

source /etc/default/stoneridge

PID=$SRHOME/srmqproxy.pid
LOG=$SRHOME/srmqproxy.log

start() {
    python $SRRUN $SRROOT/srmqproxy.py --config $CONFFILE --pidfile $PID --log $LOG
}

stop() {
    kill $(cat $PID)
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|force-reload|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|force-reload}"
    exit 2
esac
