#!/bin/bash
#
# srreporter	Stone Ridge reporter setup
#
# chkconfig: 2345 98 09
# description: srreporter is responsible for uploading results to datazilla

### BEGIN INIT INFO
# Provides: srreporter
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start and stop stoneridge reporter
# Description: stoneridge reporter uploads results
### END INIT INFO

source /etc/default/stoneridge

PID=$SRRUNDIR/srreporter.pid
LOG=$SRLOGDIR/srreporter.log

start() {
    python $SRRUN $SRROOT/srreporter.py --config $CONFFILE --pidfile $PID --log $LOG
}

stop() {
    kill $(cat $PID)
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|force-reload|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|force-reload}"
    exit 2
esac
