#!/bin/bash
#
# stoneridge_client	Stone Ridge client setup
#
# chkconfig: 2345 98 09
# description: stoneridge_client is responsible for running tests

### BEGIN INIT INFO
# Provides: stoneridge client
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start and stop stoneridge client
# Description: stoneridge client runs tests
### END INIT INFO

source /etc/default/stoneridge

DNSPID=$SRHOME/srdns.pid
DNSLOG=$SRHOME/srdns.log
WORKERPID=$SRHOME/srworker.pid
WORKERLOG=$SRHOME/srworker.log
CLEANERPID=$SRHOME/srcleaner.pid
CLEANERLOG=$SRHOME/srcleaner.log

start() {
    ip addr add $MYIP/12 dev $MYDEV
    python $SRRUN $SRROOT/srdns.py --config $CONFFILE --pidfile $DNSPID --log $DNSLOG
    python $SRRUN $SRROOT/srworker.py --config $CONFFILE --pidfile $WORKERPID --log $WORKERLOG
    python $SRRUN $SRROOT/srcleaner.py --config $CONFFILE --pidfile $CLEANERPID --log $CLEANERLOG
}

stop() {
    kill $(cat $CLEANERPID)
    kill $(cat $WORKERPID)
    kill $(cat $DNSPID)
    ip addr del $MYIP/12 dev $MYDEV
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|force-reload|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|force-reload}"
    exit 2
esac
