#!/bin/bash
#
# srscheduler	Stone Ridge pcap runner
#
# chkconfig: 2345 98 09
# description: srpcapper is responsible for running pcaps between the server \
#              and the client machines

### BEGIN INIT INFO
# Provides: srpcapper
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start and stop stoneridge pcap runner
# Description: srpcapper runs pcaps of test traffic
### END INIT INFO

source /etc/default/stoneridge

PID=$SRHOME/srpcapper.pid
LOG=$SRHOME/srpcapper.log

start() {
    python $SRRUN $SRROOT/srpcapper.py --config $CONFFILE --pidfile $PID --log $LOG
}

stop() {
    kill $(cat $PID)
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|force-reload|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|force-reload}"
    exit 2
esac
