#!/bin/bash
#
# srscheduler	Stone Ridge test scheduler
#
# chkconfig: 2345 98 09
# description: srscheduler is responsible for scheduling test runs on the \
#              various client machines that need to talk to this server

### BEGIN INIT INFO
# Provides: srscheduler
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start and stop stoneridge scheduler
# Description: srscheduler schedulers test runs on client machines
### END INIT INFO

source /etc/default/stoneridge

PID=$SRRUNDIR/srscheduler.pid
LOG=$SRLOGDIR/srscheduler.log

start() {
    python $SRRUN $SRROOT/srscheduler.py --config $CONFFILE --pidfile $PID --log $LOG --netconfig $NETCONFIG
}

stop() {
    kill $(cat $PID)
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|force-reload|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|force-reload}"
    exit 2
esac
